version: '3.9'

services:
  web:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app         
      - ./data:/app/data   
    env_file:
      - ./.env             
    networks:
      - app_network
    restart: always
    stop_grace_period: 5s
    labels:
      - "com.example.project=fastapi-compose"
      - "com.example.owner=Nebojsa"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys; urllib.request.urlopen('http://localhost:8000/'); sys.exit(0)\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app_network:
    driver: bridge
